name: flutter_supabase_template
description: "Flutter Supabase Template."
publish_to: 'none'

version: 1.0.1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.10.1
  path_provider: ^2.1.1
  path: ^1.8.3
  logging: ^1.2.0
  provider: ^6.1.1
  get_it: ^9.2.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.8
  sizer: ^3.1.3
  powersync: ^1.17.0
  go_router: ^17.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true